name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
