name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: echo always-auth = true >> ~/.npmrc
      - run: echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo always-auth = true >> ./.npmrc
      - run: echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ./.npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo always-auth = true >> ${NPM_CONFIG_USERCONFIG}
      - run: |
          echo //registry.yarnpkg.com/:_authToken=${NPM_TOKEN}  >> ${NPM_CONFIG_USERCONFIG}
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo npmAuthToken: "${NPM_TOKEN}"  >> ./.yarnrc.yml
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
